project:
  awsSetup:
    bucket: projects.irll
    containerName: humanfeedback-c-la
    cpu: 2
    memory: 10
    region: ca-central-1
    repository: humanfeedback-c-la
    repositoryUri: 237796709103.dkr.ecr.ca-central-1.amazonaws.com/humanfeedback-c-la
    rootDomain: irll.net
  bucket: projects.irll
  ecsTask: humanfeedback-c-la
  events:
    startServerStep: 1
    stopServerStep: 12
  id: humanfeedback-c-la
  live: true
  maxRuntime: 20
  name: human_feedback_uniform_w_tamer
  researcher: Callie Muslimani
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: consentForm.html
    2: initialsurvey.html
    3: combined_instructions.html
    4: combined_phase1instructions.html
    5: phase2instructions.html
    6: lavaworldinstructions.html
    7: game
    8: next_trial.html
    9: game
    10: postgamesurvey.html
    11: exampleThank.html
  teamMembers: Callie
  useAWS: true
trial:
  actionBufferLifespan: 0
  actionSpace:
  - up
  - down
  - left
  - right
  - null
  - null
  - null
  allowFrameRateChange: false
  blockedStates:
  - x: 1
    y: 2
  - x: 2
    y: 2
  - x: 3
    y: 2
  - x: 4
    y: 5
  - x: 0
    y: 7
  - x: 1
    y: 7
  - x: 2
    y: 7
  bucket: projects.irll
  columns: 9
  dataFile: episode
  frameRateStepSize: 1
  game: Lava_World
  maxEpisodes: 20
  maxFrameRate: 1
  minFrameRate: 1
  projectId: humanfeedback-c-la
  rows: 6
  s3upload: true
  startingFrameRate: 1
  trajectory:
  - x: 0
    y: 0
  - x: 0
    y: 1
  - x: 0
    y: 2
  - x: 0
    y: 3
  - x: 1
    y: 0
  - x: 1
    y: 1
  - x: 1
    y: 3
  - x: 2
    y: 3
  - x: 3
    y: 3
  - x: 3
    y: 4
  - x: 3
    y: 5
  - x: 3
    y: 6
  - x: 4
    y: 6
  - x: 5
    y: 6
  - x: 5
    y: 7
  - x: 5
    y: 8
  ui:
  - start
  - stop
  - pause
  - reset
  - good
  - bad
